-- ============================================================================
-- Master Farmer - Grindbot
-- Alliance 1-60 w/Vendoring - path index
-- ============================================================================
-- Authors: BLIZZ - Anthonyk
-- Version: 1.7.0
-- Folder: Master_Farmer_Grindbot_v1.7.0
-- ============================================================================
-- Index only. Every entry names a module that is required on demand and
-- dropped again when another is picked - see path_format.take_module. The
-- 27 routes here hold 9,223 waypoints between them, which is why none of
-- them are loaded until one is selected.
--
-- Generated. Do not hand-edit: regenerate instead.
-- ============================================================================
return {
    {
        id = "Humanlvl1_4",
        label = "Human 1-4",
        module = "grind/paths/ally160/Humanlvl1_4",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1429,
        count = 133,
        min = 1,
        max = 4,
        pull = 50,
        loop = true,
        vendors = { 1213, 190, 152 },
    },
    {
        id = "LVL1_6GnomeDwarfVendor",
        label = "Gnome/Dwarf 1-6 (Vendor)",
        module = "grind/paths/ally160/LVL1_6GnomeDwarfVendor",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1426,
        count = 271,
        min = 1,
        max = 6,
        pull = 50,
        loop = true,
        vendors = { 829 },
    },
    {
        id = "LVL1_75Herbing",
        label = "Elwynn Herb 1-75",
        module = "grind/paths/ally160/LVL1_75Herbing",
        region = "ally160",
        source = "ally160",
        kind = "herb",
        map_id = 1429,
        count = 802,
        min = 1,
        max = 75,
        pull = 50,
        loop = true,
    },
    {
        id = "Northshirelvl4_6",
        label = "Northshire 4-6",
        module = "grind/paths/ally160/Northshirelvl4_6",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1429,
        count = 151,
        min = 4,
        max = 6,
        pull = 50,
        loop = true,
        vendors = { 1213, 190, 152 },
    },
    {
        id = "ElwynnForstLVL6_9",
        label = "Elwynn Forest 6-9 (Vendor)",
        module = "grind/paths/ally160/ElwynnForstLVL6_9",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1429,
        count = 338,
        min = 6,
        max = 9,
        pull = 50,
        loop = true,
        vendors = { 66 },
    },
    {
        id = "LVL6_9GnomedwarfVendor",
        label = "Gnome/Dwarf 6-9",
        module = "grind/paths/ally160/LVL6_9GnomedwarfVendor",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1426,
        count = 387,
        min = 6,
        max = 9,
        pull = 50,
        loop = true,
    },
    {
        id = "NorthsireVendor_to_GoldshireVendor",
        label = "Northshire Vendor -> Goldshire Vendor",
        module = "grind/paths/ally160/NorthsireVendor_to_GoldshireVendor",
        region = "ally160",
        source = "ally160",
        kind = "vendor",
        map_id = 1429,
        count = 105,
        min = 6,
        max = 9,
        pull = 50,
        loop = false,
        vendors = { 66 },
    },
    {
        id = "LVL8_11GnomeDwafVendor",
        label = "Gnome/Dwarf 8-11 (Vendor)",
        module = "grind/paths/ally160/LVL8_11GnomeDwafVendor",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1426,
        count = 470,
        min = 8,
        max = 11,
        pull = 50,
        loop = true,
        vendors = { 1698 },
    },
    {
        id = "ElwynnLVL9_12",
        label = "Elwynn Forest 9-12 (Vendor)",
        module = "grind/paths/ally160/ElwynnLVL9_12",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1429,
        count = 620,
        min = 9,
        max = 12,
        pull = 50,
        loop = true,
        vendors = { 66 },
    },
    {
        id = "LVL11_14LochhModan",
        label = "Loch Modan 11-14 (Vendor)",
        module = "grind/paths/ally160/LVL11_14LochhModan",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1432,
        count = 451,
        min = 11,
        max = 14,
        pull = 50,
        loop = true,
        vendors = { 6743 },
    },
    {
        id = "WestFallLVL12_14",
        label = "Westfall 12-14",
        module = "grind/paths/ally160/WestFallLVL12_14",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1436,
        count = 202,
        min = 12,
        max = 14,
        pull = 50,
        loop = true,
    },
    {
        id = "Westfall12_14VendorRoute",
        label = "Westfall 12-14 Vendor Route",
        module = "grind/paths/ally160/Westfall12_14VendorRoute",
        region = "ally160",
        source = "ally160",
        kind = "vendor",
        map_id = 1436,
        count = 126,
        min = 12,
        max = 14,
        pull = 50,
        loop = false,
    },
    {
        id = "LVL13_17LochModanVendor",
        label = "Loch Modan 13-17 (Vendor)",
        module = "grind/paths/ally160/LVL13_17LochModanVendor",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1432,
        count = 490,
        min = 13,
        max = 17,
        pull = 50,
        loop = true,
        vendors = { 1214 },
    },
    {
        id = "LVL14_16EasywithVendorWestfall",
        label = "Westfall 14-16 Easy (Vendor)",
        module = "grind/paths/ally160/LVL14_16EasywithVendorWestfall",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1436,
        count = 435,
        min = 14,
        max = 16,
        pull = 50,
        loop = false,
        vendors = { 1668, 843 },
    },
    {
        id = "WestfallLVL14_16HARD",
        label = "Westfall 14-16 Hard",
        module = "grind/paths/ally160/WestfallLVL14_16HARD",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1436,
        count = 208,
        min = 14,
        max = 16,
        pull = 50,
        loop = true,
    },
    {
        id = "WestFallLVL16_20Bandits",
        label = "Westfall 16-20 Bandits",
        module = "grind/paths/ally160/WestFallLVL16_20Bandits",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1436,
        count = 211,
        min = 16,
        max = 20,
        pull = 50,
        loop = true,
    },
    {
        id = "LVL17_20LochModanTroggsHard",
        label = "Loch Modan 17-20 Troggs Hard",
        module = "grind/paths/ally160/LVL17_20LochModanTroggsHard",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1432,
        count = 232,
        min = 17,
        max = 20,
        pull = 50,
        loop = true,
        vendors = { 1214 },
    },
    {
        id = "P20_24WolfsSpidersVendorsinWestfall",
        label = "Duskwood 20-24 Wolves/Spiders (Vendor)",
        module = "grind/paths/ally160/P20_24WolfsSpidersVendorsinWestfall",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1436,
        count = 606,
        min = 20,
        max = 24,
        pull = 50,
        loop = false,
        vendors = { 843, 1668, 1670 },
    },
    {
        id = "LVL21_26WetlandsVendor",
        label = "Wetlands 21-26 (Vendor)",
        module = "grind/paths/ally160/LVL21_26WetlandsVendor",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1437,
        count = 534,
        min = 21,
        max = 26,
        pull = 50,
        loop = true,
        vendors = { 8305 },
    },
    {
        id = "LVL24_26DuskwoodNOVENDOR",
        label = "Duskwood 24-26",
        module = "grind/paths/ally160/LVL24_26DuskwoodNOVENDOR",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1431,
        count = 259,
        min = 24,
        max = 26,
        pull = 50,
        loop = false,
    },
    {
        id = "LVL24_27WetlandsHard",
        label = "Wetlands 24-27 Hard",
        module = "grind/paths/ally160/LVL24_27WetlandsHard",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1437,
        count = 177,
        min = 24,
        max = 27,
        pull = 50,
        loop = false,
    },
    {
        id = "DuskwoodworgenLVL24_27",
        label = "Duskwood 26-28 Worgen (Vendor)",
        module = "grind/paths/ally160/DuskwoodworgenLVL24_27",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1431,
        count = 439,
        min = 26,
        max = 28,
        pull = 50,
        loop = true,
        vendors = { 226 },
    },
    {
        id = "LVL30_35ArathiHighlandsVendor",
        label = "Arathi Highlands 30-35 (Vendor)",
        module = "grind/paths/ally160/LVL30_35ArathiHighlandsVendor",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1417,
        count = 504,
        min = 30,
        max = 35,
        pull = 50,
        loop = true,
        vendors = { 2808, 2810 },
    },
    {
        id = "LVL35_38ArathiHighlands",
        label = "Arathi Highlands 35-38",
        module = "grind/paths/ally160/LVL35_38ArathiHighlands",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1417,
        count = 223,
        min = 35,
        max = 38,
        pull = 50,
        loop = false,
    },
    {
        id = "LVL35_39STVRebalCamp",
        label = "STV 35-39 Rebel Camp",
        module = "grind/paths/ally160/LVL35_39STVRebalCamp",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1434,
        count = 291,
        min = 35,
        max = 39,
        pull = 50,
        loop = false,
    },
    {
        id = "LVL39_43STVSouth",
        label = "STV 39-43 South",
        module = "grind/paths/ally160/LVL39_43STVSouth",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1434,
        count = 163,
        min = 39,
        max = 43,
        pull = 50,
        loop = false,
    },
    {
        id = "LVL42_45Hinterlands",
        label = "Hinterlands 42-45",
        module = "grind/paths/ally160/LVL42_45Hinterlands",
        region = "ally160",
        source = "ally160",
        kind = "grind",
        map_id = 1425,
        count = 395,
        min = 42,
        max = 45,
        pull = 50,
        loop = true,
    },
}
