-- ============================================================================
-- Master Farmer - Grindbot
-- Superseded route index
-- ============================================================================
-- Authors: BLIZZ - Anthonyk
-- Version: 2.7.5
-- Folder: Master_Farmer_Grindbot
-- ============================================================================
-- Deliberately empty.
--
-- This used to index eight routes converted from the first PathTool export.
-- Every one of them was re-exported into the Alliance Grinding 1-60 set and
-- lives in grind/paths/ally160 now, carrying the same id and the same
-- waypoints plus the vendor NPC ids from that folder's README.
--
-- Because the ids matched, the catalog's deduplication already hid all eight
-- behind their ally160 twins: they were parsed, indexed and held in memory on
-- every load, and then never shown. Removing the files and emptying this index
-- drops 42 catalog entries to 34 - the 34 that were actually reachable.
--
-- The file itself stays because grind/catalog.lua, loader.lua and main.lua all
-- name it in their index lists; returning an empty table is how it says "no
-- routes here" without those three needing a special case.
-- ============================================================================
return {}
