"""Turn Alliance_FlightPath_Routes PathTool JSON into data/ek_alliance_routes.lua.

Waypoints are thinned to about 8 yards so a travel hop can follow the road
without a point every step. Spell actions on the source points are not travel
and are dropped. End tags come from the filename: inn, fp, or blank.
"""
import json
import re
from pathlib import Path

SRC = Path(r"C:\Users\ebene\Downloads\EasternKingdomAlliancePathing\Alliance_FlightPath_Routes")
OUT = Path(__file__).resolve().parents[1] / "data" / "ek_alliance_routes.lua"
THIN = 8.0


def tag(name):
    low = name.lower()
    if "inn" in low:
        return "inn"
    if "fp" in low:
        return "fp"
    return ""


def thin(wps):
    kept = []
    last = None
    last_i = len(wps) - 1
    for i, w in enumerate(wps):
        x, y, z = float(w["x"]), float(w["y"]), float(w["z"])
        if last is None:
            kept.append((x, y, z))
            last = (x, y)
            continue
        dx, dy = x - last[0], y - last[1]
        if (dx * dx + dy * dy) >= (THIN * THIN) or i == last_i:
            kept.append((x, y, z))
            last = (x, y)
    return kept


def main():
    files = sorted(SRC.glob("*.json"), key=lambda p: p.name.lower())
    routes = []
    raw_n = 0
    thin_n = 0
    for path in files:
        data = json.loads(path.read_text(encoding="utf-8"))
        wps = data.get("waypoints") or []
        raw_n += len(wps)
        pts = thin(wps)
        if len(pts) < 2:
            continue
        thin_n += len(pts)
        stem = path.stem.strip()
        parts = re.split(r"_to_", stem, maxsplit=1, flags=re.IGNORECASE)
        a = tag(parts[0]) if parts else ""
        b = tag(parts[1]) if len(parts) > 1 else ""
        routes.append((stem, a, b, int(data.get("map_id") or 0), pts))

    lines = [
        "-- ============================================================================",
        "-- Master Farmer - Grindbot",
        "-- Alliance Eastern Kingdoms inn and flight-path roads",
        "-- ============================================================================",
        "-- Version: 2.133.0",
        "-- Generated by tools/build_alliance_routes.py from PathTool JSON.",
        "-- Each route: name, end tags (inn / fp / empty), map id, flat x,y,z.",
        "-- Points are about 8 yards apart. Spell actions on the source are omitted.",
        "-- ============================================================================",
        "return {",
    ]
    for name, a, b, map_id, pts in routes:
        flat = ",".join(f"{v:.1f}" for p in pts for v in p)
        lines.append(
            '    {"%s","%s","%s",%d,%s},' % (name, a, b, map_id, flat)
        )
    lines.append("}")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"routes={len(routes)} raw_points={raw_n} kept={thin_n} bytes={OUT.stat().st_size}")


if __name__ == "__main__":
    main()
